name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update &&
           sudo apt-get install -y g++ python3.8-dev make python3-pip
    - name: install pybind11
      run: python3 -m pip install pybind11 setuptools
    - name: make
      run: make CXX=g++-9
    - name: sdist
      run: python3 setup.py sdist
    - uses: actions/upload-artifact@v2
      with:
        name: ffcache
        path: |
          dist/*

  test:
    runs-on: ubuntu-18.04
    needs: build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: ffcache
    - name: install dependencies
      run: sudo apt-get update &&
           sudo apt-get install -y g++ python3.8
    - name: install
      run: pip3 install dist/*
    - name: test
      run: python3 -c 'import ffcache'
