name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update &&
           sudo apt-get install -y g++ python3.8-dev python3-pip
    - name: install with pip
      run: python3 -m pip install pybind11 setuptools wheel
    - name: make
      run: make -j8
    - name: sdist
      run: python3 setup.py sdist
    - name: install
      run: python3 -m pip install *.tar.gz
    - name: test
      run: cd ../ && python3 -c 'import ffcache'
    - uses: actions/upload-artifact@v2
      with:
        name: ffcache
        path: |
          dist/*